# Purity Jekyll Theme
#=====================

## Plugin Configurations

kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed


## Globals

url:     http://guyincognito.io
baseurl: /

title:    Guy Incognito
tagline:  Write-ups for stuff I would forget otherwise                             #Optional
timezone: Europe/Berlin

author:
  name:     Guy Incognito
  link:     http://www.guyincognito.io
  photo:
    alt:    Avatar from GitHub
    remote: https://avatars3.githubusercontent.com/u/1577944
#    local: assets/img/photo.jpg

github:
  user: AllesCoolAllesBestens
  repo: AllesCoolAllesBestens.github.io


## Theme and Layout

# Defaults:
# ---------
# theme:
#   tooltips:    enabled
#   hover_light: enabled
#
# fonts:
#   base: Noto Sans
#   head: Montserrat
#   mono: Ubuntu Mono
#
# layout:
#   header:
#     style: scroll # (can be: scroll | fixed | disabled)
#   footer:
#     style: scroll # (can be: scroll | fixed | disabled)
#   sidebar:
#     style: left   # (can be: left | right | disabled)

layout:
  header:
    style: fixed
  sidebar:
    style: left

topmenu:
  Test Pages:
    headings_test:
      local: tests/headings.md

sidemenu:
  Test Pages:
    code_test:
      local: tests/code.md
  Links:
    personal:
      url:   /
      title: My website
      icon:  user
    split_1:
      type:  spacer
